-- === Supabase Schema Snapshot (RLS Policies) ===

| schemaname | tablename         | policyname                                              | cmd    | roles    | qual                                                                                                                                                                                                                                               | with_check                                                                                                                                                                           |
| ---------- | ----------------- | ------------------------------------------------------- | ------ | -------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| public     | conversations     | conversations_insert_creator                            | INSERT | {public} | null                                                                                                                                                                                                                                               | (auth.uid() = created_by)                                                                                                                                                            |
| public     | conversations     | conversations_select_participant                        | SELECT | {public} | (EXISTS ( SELECT 1
   FROM participants
  WHERE ((participants.conversation_id = conversations.id) AND (participants.user_id = auth.uid()))))                                                                                                      | null                                                                                                                                                                                 |
| public     | message_status    | Users can update message status for their messages      | INSERT | {public} | null                                                                                                                                                                                                                                               | (user_id = auth.uid())                                                                                                                                                               |
| public     | message_status    | Users can update their own message status               | UPDATE | {public} | (user_id = auth.uid())                                                                                                                                                                                                                             | null                                                                                                                                                                                 |
| public     | message_status    | Users can view message status in their conversations    | SELECT | {public} | (EXISTS ( SELECT 1
   FROM participants
  WHERE ((participants.conversation_id = ( SELECT messages.conversation_id
           FROM messages
          WHERE (messages.id = message_status.message_id))) AND (participants.user_id = auth.uid())))) | null                                                                                                                                                                                 |
| public     | messages          | Users can send messages to their conversations          | INSERT | {public} | null                                                                                                                                                                                                                                               | ((sender_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM participants
  WHERE ((participants.conversation_id = messages.conversation_id) AND (participants.user_id = auth.uid()))))) |
| public     | messages          | Users can view messages in their conversations          | SELECT | {public} | (EXISTS ( SELECT 1
   FROM participants
  WHERE ((participants.conversation_id = messages.conversation_id) AND (participants.user_id = auth.uid()))))                                                                                              | null                                                                                                                                                                                 |
| public     | participants      | participants_delete_own                                 | DELETE | {public} | (auth.uid() = user_id)                                                                                                                                                                                                                             | null                                                                                                                                                                                 |
| public     | participants      | participants_insert_own                                 | INSERT | {public} | null                                                                                                                                                                                                                                               | (auth.uid() = user_id)                                                                                                                                                               |
| public     | participants      | participants_select_own                                 | SELECT | {public} | (auth.uid() = user_id)                                                                                                                                                                                                                             | null                                                                                                                                                                                 |
| public     | translations      | Users can view translations in their conversations      | SELECT | {public} | (EXISTS ( SELECT 1
   FROM participants
  WHERE ((participants.conversation_id = ( SELECT messages.conversation_id
           FROM messages
          WHERE (messages.id = translations.message_id))) AND (participants.user_id = auth.uid()))))   | null                                                                                                                                                                                 |
| public     | typing_indicators | Users can manage their own typing indicators            | ALL    | {public} | (auth.uid() = user_id)                                                                                                                                                                                                                             | null                                                                                                                                                                                 |
| public     | typing_indicators | Users can view typing indicators in their conversations | SELECT | {public} | (EXISTS ( SELECT 1
   FROM participants
  WHERE ((participants.conversation_id = typing_indicators.conversation_id) AND (participants.user_id = auth.uid()))))                                                                                     | null                                                                                                                                                                                 |
| public     | users             | Users can update own profile                            | UPDATE | {public} | (auth.uid() = id)                                                                                                                                                                                                                                  | null                                                                                                                                                                                 |
| public     | users             | Users can view all profiles                             | SELECT | {public} | true                                                                                                                                                                                                                                               | null                                                                                                                                                                                 |
| public     | users             | Users can view own profile                              | SELECT | {public} | (auth.uid() = id)                                                                                                                                                                                                                                  | null                                                                                                                                                                                 |
